apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kpi_rsm.fullname" . }}-config
  labels:
    app: {{ template "kpi_rsm.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
{{- if .Values.logging }}
{{ toYaml .Values.logging | indent 4 }}
{{- end}}
  config.json: |-
{{ .Values.config.kpimon.config_json | toPrettyJson | indent 4 }}
